name: TprParser

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: build job
      run: |
        set -x
        cd TprParser
        cmake . -DCMAKE_BUILD_TYPE=Release
        cmake --build . --target INSTALL --config Release

