name: TprParser

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

    
jobs:
  LinuxBuild:
    runs-on: ubuntu-latest

    steps:
    - name: git source
      uses: actions/checkout@v2

    - name: set python version
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: build job
      run: |
        set -x
        python -m pip install numpy
        cd TprParser
        cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$(pwd)
        make 
        make install 

  WindowsBuild:
    runs-on: windows-latest

    steps:
    - name: git source
      uses: actions/checkout@v2

    - name: set python version
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: build job
      run: |
        python -m pip install numpy
        cd TprParser
        cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$(pwd)
        cmake --build . --target INSTALL --config Release


  Mingw64Build:
    runs-on: windows-latest

    steps:
    - name: git source
      uses: actions/checkout@v2

    - name: Set up MinGW64
      uses: egor-tensin/setup-mingw@v2
      with:
        platform: x64

    - name: set python version
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: build job
      run: |
        set -x
        python -m pip install numpy
        cd TprParser
        cmake . -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$(pwd)
        mingw64-make 
        mingw64-make install 
        